name: Validate Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: "latest"

      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Lint Project
        run: pnpm lint

      - name: Check TS types
        run: pnpm tscheck

      - name: Build Project
        run: pnpm build